"""
Generate Markdown load report after CSV ingestion.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

from loading.config import LOAD_REPORT_PATH, TARGET_SCHEMA
from loading.copy_load import TableLoadResult
from loading.validate import ValidationReport

logger = logging.getLogger("supplysight.postgres.loading.report")


def build_load_report(
    load_results: Sequence[TableLoadResult],
    validation: ValidationReport,
    *,
    total_elapsed: float,
    success: bool,
) -> str:
    """Compose load_report.md content."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    status = "SUCCESS" if success else "FAILED"

    lines: list[str] = [
        "# SupplySight AI — Data Load Report",
        "",
        f"**Generated:** {now}",
        f"**Target schema:** `{TARGET_SCHEMA}`",
        f"**Pipeline status:** **{status}**",
        f"**Total elapsed:** {total_elapsed:.2f}s",
        "",
        "## 1. Load Summary",
        "",
        "| Table | Method | CSV Rows | Inserted | Skipped | Seconds | Notes / Errors |",
        "|-------|--------|----------|----------|---------|---------|----------------|",
    ]

    for r in load_results:
        notes = "; ".join(r.notes) if r.notes else ""
        if r.error:
            notes = f"{notes}; ERROR: {r.error}".strip("; ")
        lines.append(
            f"| `{r.table}` | {r.method} | {r.rows_in_csv:,} | "
            f"{r.rows_inserted:,} | {r.rows_skipped:,} | {r.elapsed_seconds:.2f} | {notes} |"
        )

    lines.extend(
        [
            "",
            "## 2. Table Row Counts (`SELECT COUNT(*)`)",
            "",
            "| Table | Row Count |",
            "|-------|-----------|",
        ]
    )
    for table, count in validation.row_counts.items():
        lines.append(f"| `{TARGET_SCHEMA}.{table}` | {count:,} |")

    lines.extend(
        [
            "",
            "## 3. Validation Results",
            "",
        ]
    )
    if not validation.issues:
        lines.append("All checks passed: foreign keys, duplicate PKs, null PKs.")
    else:
        lines.extend(
            [
                "| Table | Check | Severity | Count | Detail |",
                "|-------|-------|----------|-------|--------|",
            ]
        )
        for issue in validation.issues:
            lines.append(
                f"| `{issue.table}` | `{issue.check}` | {issue.severity} | "
                f"{issue.count:,} | {issue.detail} |"
            )

    lines.extend(
        [
            "",
            "## 4. Notes",
            "",
            "- Only normalized CSVs from `database/normalized_data/` were loaded.",
            "- Raw DataCo extract was not loaded.",
            "- Empty placeholder files (`warehouses`, `vendors`, `inventory`, "
            "`vendor_products`) insert 0 rows by design.",
            "- No business values were cleaned or transformed during load.",
            "",
            "---",
            "",
            "*Generated by `database/postgres/loading/pipeline.py`*",
            "",
        ]
    )
    return "\n".join(lines)


def write_load_report(
    load_results: Sequence[TableLoadResult],
    validation: ValidationReport,
    *,
    total_elapsed: float,
    success: bool,
    output_path: Path | None = None,
) -> Path:
    """Write the load report to disk."""
    path = output_path or LOAD_REPORT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    content = build_load_report(
        load_results,
        validation,
        total_elapsed=total_elapsed,
        success=success,
    )
    path.write_text(content, encoding="utf-8")
    logger.info("Load report written: %s", path)
    return path
